version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo
    command: --replSet rs0
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - /Users/sijunfeng/data/docker/mongodata:/data/db
