version: "3"

services:
  server:
    env_file:
      - ".env.docker"
    build: .
    ports:
      - "3003:3003"
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    command: --replSet rs0
    ports:
      - "27017:27017"
      - "28017:28017"
    volumes:
      - /Users/sijunfeng/data/docker/mongodata:/data/db
